// Copyright (c) Microsoft. All rights reserved.

namespace Microsoft.TypeChat;

/// <summary>
/// Normalized token usage reported by a language model for a single completion. Values are mapped
/// from the underlying API response so callers don't have to special-case the differences between
/// the Chat Completions API (prompt/completion tokens) and the Responses API (input/output tokens).
/// </summary>
public class TokenUsage
{
    /// <summary>
    /// Creates a new <see cref="TokenUsage"/>.
    /// </summary>
    public TokenUsage(
        int promptTokens,
        int completionTokens,
        int totalTokens,
        int? cachedPromptTokens = null,
        int? reasoningTokens = null)
    {
        PromptTokens = promptTokens;
        CompletionTokens = completionTokens;
        TotalTokens = totalTokens;
        CachedPromptTokens = cachedPromptTokens;
        ReasoningTokens = reasoningTokens;
    }

    /// <summary>
    /// Number of tokens consumed by the prompt/input.
    /// </summary>
    public int PromptTokens { get; }

    /// <summary>
    /// Number of tokens generated in the completion/output.
    /// </summary>
    public int CompletionTokens { get; }

    /// <summary>
    /// Total number of tokens billed for the request (prompt + completion).
    /// </summary>
    public int TotalTokens { get; }

    /// <summary>
    /// Prompt tokens served from cache (a subset of <see cref="PromptTokens"/>), when the API
    /// reports it. Cached input tokens are typically billed at a reduced rate.
    /// </summary>
    public int? CachedPromptTokens { get; }

    /// <summary>
    /// Reasoning tokens generated by a reasoning model such as o1/o3 (a subset of
    /// <see cref="CompletionTokens"/>), when the API reports it.
    /// </summary>
    public int? ReasoningTokens { get; }
}
